import type { Metadata } from 'next'
import { Silkscreen } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import ThemeProvider from '@/context/ThemeProvider'
import '../styles/globals.css'

const silkScreen = Silkscreen({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Gamebud',
  description: 'Generated by ❤️',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" className={silkScreen.className}>
        <body>
          <ThemeProvider
            attribute='class'
            forcedTheme='dark'
            storageKey='gamebud-theme'
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
